### ISSUE TITLE
Update http://csv.togeojson.com/

### ISSUE THREAD

**Issue by hugovk** [gavinr/csv-to-geojson#10]
I was going to create an issue or PR that blank lines in the CSV (I had a blank line at the end) result in invalid geoJSON because it ends with `{"type":"Feature","geometry":{},"properties":{}}]}`.

But I see the latest master has already fixed this in https://github.com/gavinr/csv-to-geojson/pull/7 :)

Please could you update the code on the released site?

Thanks for this handy tool!

(One suggestion is to rename your master branch to gh-pages and use [GitHub Pages](https://pages.github.com/) to host directly on http://csv.togeojson.com/, so no need to deploy in the future -- it's always up to date.)

**Comment by gavinr** [comment]
yes - you're right I should move this to GH-pages. Thanks for opening the issue!

**Comment by robertleeplummerjr** [comment]
The first step is creating a branch from master "gh-pages", then you'll seamlessly have:
https://gavinr.github.io/csv-to-geojson

Example:
repo: https://github.com/robertleeplummerjr/Leaflet.glify
site: http://robertleeplummerjr.github.io/Leaflet.glify

**Comment by gavinr** [comment]
Yep - thanks for the info. I'm aware of the process just tying to cleanup some stuff before I do so.

**Comment by robertleeplummerjr** [comment]
I figured you did but I greedily was trying to show a lib where I use your fantastic site.

**Comment by gavinr** [comment]
@robertleeplummerjr @hugovk the current repo code is now running on http://gavinr.github.io/csv-to-geojson. In the long term I need to get http://csv.togeojson.com to point to here, but this requires DNS changes, so just wanted to let you know in the short term.

**Comment by robertleeplummerjr** [comment]
I could be wrong, but I believe this is a "huzza" moment.

**Comment by robertleeplummerjr** [comment]
huzza!

**Comment by robertleeplummerjr** [comment]
@gavinr thank you for your hard work!

**Comment by gavinr** [comment]
content from this repo is now directly accessed via http://csv.togeojson.com

**Comment by robertleeplummerjr** [comment]
![](https://media.giphy.com/media/DpB9NBjny7jF1pd0yt2/giphy.gif)
(awesome!!!)
