### ISSUE TITLE
Spaces in first line of CSV cause bad or no geometry

### ISSUE THREAD

**Issue by bchappell61** [gavinr/csv-to-geojson#13]
I tried to use a simple CSV file, and it forgot to create geometry type & coordinates. However it did leave the coordinates in the properties but it saved them as strings.

Example file used:

```
Street, City, State, Zip, Misc, Lat, Lon 
800 North Pearl St, Menards, NY, 12204, Work, 42.67948646, -73.73575897
```

What I got back:

```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      **"geometry": {},**
      "properties": {
        "Street": " 800 North Pearl St",
        " City": " Menards",
        " State": " NY",
        " Zip": " 12204",
        " Misc": " Work",
        "  latitude": " 42.67948646",
        " longitude ": " -73.73575897"   
      }
```

It should be this:

{
   "type": "FeatureCollection",
   "features": [
  {
    "type": "Feature",
    **"geometry": {
       "type": "Point",
       "coordinates":  [ -73.73575897,42.67948646 ]
    },**
    "properties": {
    "Street":" 800 North Pearl St",
    "City":" Menards",
    "State":" NY",

**Comment by gavinr** [comment]
@bchappell61 thanks for the report. Looks like the spaces in your first line are causing the error. A workaround is to remove those spaces:

```
Street,City,State,Zip,Misc,Lat,Lon
800 North Pearl St,Menards,NY,12204,Work,42.67948646,-73.73575897
```
... and that seems to work.

But I'll leave this issue open because we should be handling the case where there are spaces in the column header. PRs always welcome :)

**Comment by bchappell61** [comment]
Wow, fast response and an easy fix.  Thanks.

**Comment by marcgarygray** [comment]
I'd love to tackle this! PR coming soon.
