### ISSUE TITLE
Prevent quotes around certain properties

### ISSUE THREAD

**Issue by kpennell** [gavinr/csv-to-geojson#5]
I have a unix time stamp as a date property in my geojson.  With the quote around the timestamp, it can't read it right (fairly obvious). Same with currency.  Is there a way to keep certain properties from having quotes around them?

Thanks, btw, for this.

**Comment by gavinr** [comment]
Hi @kpennell, can you please post a snippet of the geojson in question?

Thanks,
Gavin

**Comment by kpennell** [comment]
Thanks, Gavin.  Awesome tool.

sample:

There was no quotes around the date timestap or price. Any ideas how to
change this so integers don't get quotes?

{
         "type":"Feature",
         "geometry":{
            "type":"Point",
            "coordinates":[
               -122.4103922,
               37.78252331
            ]
         },
         "properties":{
            "venue":"venue",
            "venue_url":"www.website.com",
            "id":"show30",
            "date":"1429498800000",
            "artist":"artist",
            "artist_url":"http://www.sts.com",
            "price":"52",
            "ticket_url":"www.test.com",
            "tags":"Alternative Rock",
            "stream_url":"stream.url",
            "artwork_url":"\"http://test.com\""
         }
      },
