### ISSUE TITLE
Trailing Newlines Aren't Ignored

### ISSUE THREAD

**Issue by thedeerchild** [gavinr/csv-to-geojson#6]
If there's a trailing newline (empty row) at the end of the CSV data, a feature with no geometry will be created, breaking a lot of GeoJSON parsers (such as [GeoJSON Lint](http://geojsonlint.com/) and GitHub's display functionality).

**Comment by gavinr** [comment]
Thanks @thedeerchild! Can you please post an example CSV of what you're talking about?
