### ISSUE TITLE
readme should warn data is automatically uploaded to a public github gist

### ISSUE THREAD

**Issue by alancwoo** [gavinr/csv-to-geojson#8]
Users should ideally read the source, but you should indicate in your readme that public anonymous gists are created with the input data.

It's possible someone may be working with sensitive data and could, without realizing, have it uploaded publicly to github gists.

**Comment by gavinr** [comment]
Hi @alancwoo, great point. Or maybe just a link AFTER it is converted to optionally create a map/gist with it?

I'd welcome a pull request that does that. Or I'll try to get to it sometime. Thanks!

**Comment by hugovk** [comment]
I was also surprised a public anonymous Gist was made, so PR #9 makes the link more explicit.

**Comment by gavinr** [comment]
This is a good stop-gap for now, so I'll merge it in. In the long term I'd like to have an option (like a button) after that would allow the user to create a gist. Thank you for the PR!
